### ISSUE TITLE
numRows and count(cells) not equal

### ISSUE THREAD

**Issue by iamchathu** [alemohamad/ci-excel-reader#1]
``` php
$numRows = $worksheet['numRows']; 
echo "Num Rows ".$numRows;
$cells = $worksheet['cells']; 

echo "Count ".count($cells);
```

These two give diffrent out put

0
65535

**Comment by alemohamad** [comment]
Thanks for your issue, but I'm not maintaining the project anymore. If you'd like to propose a fix, send a PR and I'll check it out.
