### ISSUE TITLE
PHP 4 style constructors (methods that have the same name as the class they are defined in) are deprecated

### ISSUE THREAD

**Issue by ansharfirman** [alemohamad/ci-excel-reader#3]
I used PHP 7.
and inform that
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Excel_reader has a deprecated constructor in /var/www/html/ja1/application/libraries/Excel_reader.php on line 103

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; OLERead has a deprecated constructor in /var/www/html/ja1/application/libraries/oleread.inc.php on line 37

**Comment by alemohamad** [comment]
I recommend you to look into https://packagist.org/packages/phpoffice/phpexcel.
This repo is abandoned. I should make a note about it, because it's truly old. Thanks for your interest!
