### ISSUE TITLE
file is not redable exception

### ISSUE THREAD

**Issue by vilaskrish** [alemohamad/ci-excel-reader#4]
I am using windows 7 os.

I am getting error "The filename ./uploads/sampleData.xls is not readable" exception 
My Code is
$this->load->library('Excel_reader');
$this->excel_reader->read('./uploads/sampleData.xls');
$worksheet = $this->Excel_reader->sheets[0];

**Comment by subikar** [comment]
I am having the same issue not readable even I given 777 permission but still not readable.

**Comment by alemohamad** [comment]
Thanks for your issues, but I'm not maintaining the project anymore. If you'd like to propose a fix, send a PR and I'll check it out.
